name: liquid_bid
description: LiquidBid marketplace for auctions, discounts, price watch, and AI pricing.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.6.6
  shared_preferences: ^2.2.2
  flutter_animate: ^4.5.0
  google_fonts: ^6.1.0
  carousel_slider: ^4.2.1
  flip_card: ^0.7.0
  lottie: ^2.7.0
  flutter_local_notifications: ^17.1.2
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
