name: trend_electronics_store
description: Flutter Glassmorphism e-commerce experience for trending electronics.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  transparent_image: ^2.0.1
  geolocator: ^9.0.2
  geocoding: ^2.2.0
  http: ^1.2.1
  url_launcher: ^6.2.5
  flutter_blurhash: ^0.8.2
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/mock/
    - assets/images/
