/*
  هذا الملف يضم الترجمة العربية للنصوص المستخدمة في الواجهات.
  يمكن إضافة مفاتيح أو تعديل الصياغة بسهولة عند توسعة المحتوى.
*/
const Map<String, String> ar = {
  'app.title': 'ثماني للمزادات',
  'splash.loading': 'جارٍ تجهيز المزادات...',
  'splash.welcome': 'اكتشف مناقصات حصرية',
  'auth.login': 'تسجيل الدخول',
  'auth.signup': 'إنشاء حساب',
  'auth.name': 'الاسم الكامل',
  'auth.email': 'البريد الإلكتروني',
  'auth.phone': 'رقم الهاتف',
  'auth.password': 'كلمة المرور',
  'auth.confirmPassword': 'تأكيد كلمة المرور',
  'auth.guest': 'الدخول كضيف',
  'auth.noAccount': 'ليس لديك حساب؟',
  'auth.haveAccount': 'لديك حساب مسبقاً؟',
  'auth.remember': 'تذكرني',
  'auth.loginSuccess': 'مرحباً بعودتك!',
  'auth.signupSuccess': 'تم إنشاء الحساب بنجاح',
  'auth.logout': 'تسجيل الخروج',
  'auth.guestWelcome': 'تتصفح كضيف',
  'auth.error': 'خطأ في المصادقة',
  'home.title': 'مزادات مباشرة',
  'home.search': 'ابحث عن مزاد',
  'home.aiHighlight': 'اقتراح الذكاء الاصطناعي',
  'home.pullRefresh': 'اسحب للتحديث',
  'home.showFilters': 'عوامل التصفية',
  'home.resetFilters': 'إعادة تعيين',
  'home.priceRange': 'نطاق السعر',
  'home.sortBy': 'ترتيب حسب',
  'home.sortRecent': 'الأحدث',
  'home.sortEnding': 'ينتهي قريباً',
  'home.sortPrice': 'الأقل سعراً',
  'home.favoriteAdded': 'تمت الإضافة إلى المفضلة',
  'home.favoriteRemoved': 'تمت الإزالة من المفضلة',
  'home.undo': 'تراجع',
  'home.bidNow': 'زايد الآن',
  'home.currentPrice': 'السعر الحالي',
  'home.startPrice': 'سعر البداية',
  'home.countdown': 'ينتهي خلال',
  'home.noCountdown': 'شراء مباشر',
  'home.empty': 'لا توجد عناصر',
  'home.categories': 'الفئات',
  'home.scrollTop': 'أعلى',
  'category.cars': 'سيارات',
  'category.houses': 'منازل',
  'category.lands': 'أراضي',
  'category.electronics': 'إلكترونيات',
  'category.antiques': 'تحف',
  'details.title': 'تفاصيل العنصر',
  'details.description': 'الوصف',
  'details.aiBox': 'رؤى الذكاء الاصطناعي',
  'details.pause': 'إيقاف',
  'details.resume': 'متابعة',
  'details.next': 'التالي',
  'details.previous': 'السابق',
  'details.placeBid': 'تقديم مزايدة',
  'details.addToWishlist': 'أضف إلى المفضلة',
  'details.removeFromWishlist': 'إزالة من المفضلة',
  'details.share': 'مشاركة العنصر',
  'details.similar': 'عناصر مشابهة',
  'details.addedWishlist': 'تمت الإضافة إلى المفضلة',
  'details.removedWishlist': 'تمت الإزالة من المفضلة',
  'wishlist.title': 'المفضلة',
  'wishlist.empty': 'قائمة المفضلة فارغة',
  'wishlist.refresh': 'تحديث المفضلة',
  'mybids.title': 'مزايداتي',
  'mybids.empty': 'لا توجد مزايدات بعد',
  'mybids.refresh': 'تحديث المزادات',
  'mybids.lastBid': 'آخر مزايدة',
  'additem.title': 'إضافة مناقصة',
  'additem.name': 'عنوان العنصر',
  'additem.description': 'الوصف',
  'additem.price': 'سعر البداية',
  'additem.auction': 'تفعيل عدّاد المزاد',
  'additem.duration': 'مدة المزاد (بالدقائق)',
  'additem.addImage': 'إضافة صورة',
  'additem.submit': 'إرسال العنصر',
  'additem.success': 'تمت إضافة العنصر بنجاح',
  'additem.failure': 'فشل في إضافة العنصر',
  'settings.title': 'الإعدادات',
  'settings.language': 'اللغة',
  'settings.theme': 'الوضع اللوني',
  'settings.darkMode': 'الوضع الداكن',
  'settings.lightMode': 'الوضع الفاتح',
  'settings.systemMode': 'حسب النظام',
  'settings.notifications': 'الإشعارات (قريباً)',
  'settings.offline': 'وضع عدم الاتصال',
  'settings.about': 'حول التطبيق',
  'settings.version': 'الإصدار 1.0.0',
  'settings.tutorial': 'جولة تفاعلية',
  'settings.quickActions': 'إجراءات سريعة',
  'settings.apply': 'تطبيق',
  'common.cancel': 'إلغاء',
  'common.save': 'حفظ',
  'common.search': 'بحث',
  'common.more': 'المزيد',
  'common.yes': 'نعم',
  'common.no': 'لا',
  'common.minutes': 'دقيقة',
  'nav.home': 'الرئيسية',
  'nav.wishlist': 'المفضلة',
  'nav.mybids': 'مزايداتي',
  'nav.settings': 'الإعدادات',
  'validators.required': 'هذا الحقل مطلوب',
  'validators.email': 'الرجاء إدخال بريد إلكتروني صحيح',
  'validators.phone': 'يجب أن يكون الهاتف من 8 إلى 15 رقماً',
  'validators.password': 'كلمة المرور 8 أحرف على الأقل مع حروف كبيرة وصغيرة ورقم ورمز',
  'validators.price': 'السعر يجب أن يكون موجباً',
  'snackbar.error': 'حدث خطأ ما',
  'snackbar.success': 'تم الحفظ بنجاح',
  'tutorial.step1': 'اسحب البطاقات لاستكشاف المزادات',
  'tutorial.step2': 'أضف المفضلة بنقرة واحدة',
  'tutorial.step3': 'بدّل اللغة والوضع بسهولة',
  'notifications.placeholder': 'سيتم عرض الإشعارات هنا قريباً',
  'offline.placeholder': 'تم تفعيل وضع عدم الاتصال باستخدام التخزين المحلي',
  'weak.connection': 'تمت محاكاة اتصال ضعيف',
  'coach.start': 'ابدأ الجولة',
  'coach.next': 'التالي',
  'coach.done': 'إنهاء',
  'ai.summary_1': 'ملخص الذكاء: طلب مرتفع متوقع.',
  'ai.summary_2': 'ملخص الذكاء: قيمة مستقرة بنمو معتدل.',
  'ai.summary_3': 'ملخص الذكاء: راجع تكاليف الصيانة.',
  'ai.summary_4': 'ملخص الذكاء: عنصر نادر يهم الجامعين.',
  'ai.summary_5': 'ملخص الذكاء: مزايدات تنافسية متوقعة.',
  'ai.demand_1': 'مؤشر الطلب: منافسة منخفضة حالياً.',
  'ai.demand_2': 'مؤشر الطلب: اهتمام متوازن من المشترين.',
  'ai.demand_3': 'مؤشر الطلب: عدة مزايدين يراقبون.',
  'ai.rarity_1': 'الندرة: عنصر شائع في السوق.',
  'ai.rarity_2': 'الندرة: غير شائع قليلاً، فرصة جيدة.',
  'ai.rarity_3': 'الندرة: نادر على مستوى المناطق.',
  'ai.rarity_4': 'الندرة: توافر محدود.',
  'ai.rarity_5': 'الندرة: مستوى يهم الهواة.',
  'ai.rarity_6': 'الندرة: نسخة فريدة.',
  'ai.rarity_7': 'الندرة: طلب موسمي مرتفع.',
  'ai.tip_1': 'نصيحة: زد المزايدة قبل دقيقتين من النهاية.',
  'ai.tip_2': 'نصيحة: أضف ملحقات مرتبطة لزيادة القيمة.',
  'ai.tip_3': 'نصيحة: تحقق من تقارير الفحص.',
  'ai.tip_4': 'نصيحة: تفاوض على شروط التسليم مبكراً.',
  'ai.warning_1': 'تحذير: راقب القفزات المفاجئة في السعر.',
  'ai.warning_2': 'تحذير: قد يُغلق المزاد مبكراً.',
};
