/*
  هذا الملف يحتوي الترجمة الإنجليزية لكل النصوص المستخدمة في التطبيق.
  يمكن إضافة مفاتيح جديدة أو تحديث الحالية عند توسعة الواجهة.
*/
const Map<String, String> en = {
  'app.title': 'Thmani Auctions',
  'splash.loading': 'Preparing auctions...',
  'splash.welcome': 'Discover exclusive tenders',
  'auth.login': 'Login',
  'auth.signup': 'Create Account',
  'auth.name': 'Full Name',
  'auth.email': 'Email',
  'auth.phone': 'Phone Number',
  'auth.password': 'Password',
  'auth.confirmPassword': 'Confirm Password',
  'auth.guest': 'Continue as Guest',
  'auth.noAccount': 'Don\'t have an account?',
  'auth.haveAccount': 'Already have an account?',
  'auth.remember': 'Remember me',
  'auth.loginSuccess': 'Welcome back!',
  'auth.signupSuccess': 'Account created successfully',
  'auth.logout': 'Logout',
  'auth.guestWelcome': 'Browsing as guest',
  'auth.error': 'Authentication error',
  'home.title': 'Live Auctions',
  'home.search': 'Search auctions',
  'home.aiHighlight': 'AI Suggestion',
  'home.pullRefresh': 'Pull to refresh auctions',
  'home.showFilters': 'Filters',
  'home.resetFilters': 'Reset',
  'home.priceRange': 'Price Range',
  'home.sortBy': 'Sort by',
  'home.sortRecent': 'Most recent',
  'home.sortEnding': 'Ending soon',
  'home.sortPrice': 'Lowest price',
  'home.favoriteAdded': 'Added to favorites',
  'home.favoriteRemoved': 'Removed from favorites',
  'home.undo': 'Undo',
  'home.bidNow': 'Bid Now',
  'home.currentPrice': 'Current price',
  'home.startPrice': 'Starting price',
  'home.countdown': 'Ends in',
  'home.noCountdown': 'Buy now',
  'home.empty': 'No items found',
  'home.categories': 'Categories',
  'home.scrollTop': 'Top',
  'category.cars': 'Cars',
  'category.houses': 'Houses',
  'category.lands': 'Lands',
  'category.electronics': 'Electronics',
  'category.antiques': 'Antiques',
  'details.title': 'Item Details',
  'details.description': 'Description',
  'details.aiBox': 'AI Insights',
  'details.pause': 'Pause',
  'details.resume': 'Resume',
  'details.next': 'Next',
  'details.previous': 'Previous',
  'details.placeBid': 'Place a bid',
  'details.addToWishlist': 'Add to wishlist',
  'details.removeFromWishlist': 'Remove from wishlist',
  'details.share': 'Share item',
  'details.similar': 'Similar items',
  'details.addedWishlist': 'Added to wishlist',
  'details.removedWishlist': 'Removed from wishlist',
  'wishlist.title': 'Favorites',
  'wishlist.empty': 'Wishlist is empty',
  'wishlist.refresh': 'Refresh wishlist',
  'mybids.title': 'My Bids',
  'mybids.empty': 'No bids yet',
  'mybids.refresh': 'Refresh bids',
  'mybids.lastBid': 'Last bid',
  'additem.title': 'Add Tender',
  'additem.name': 'Item Title',
  'additem.description': 'Description',
  'additem.price': 'Starting Price',
  'additem.auction': 'Enable auction countdown',
  'additem.duration': 'Auction duration (minutes)',
  'additem.addImage': 'Add image',
  'additem.submit': 'Submit item',
  'additem.success': 'Item added successfully',
  'additem.failure': 'Failed to add item',
  'settings.title': 'Settings',
  'settings.language': 'Language',
  'settings.theme': 'Theme',
  'settings.darkMode': 'Dark mode',
  'settings.lightMode': 'Light mode',
  'settings.systemMode': 'System default',
  'settings.notifications': 'Notifications (placeholder)',
  'settings.offline': 'Offline mode',
  'settings.about': 'About',
  'settings.version': 'Version 1.0.0',
  'settings.tutorial': 'Interactive tutorial',
  'settings.quickActions': 'Quick actions',
  'settings.apply': 'Apply',
  'common.cancel': 'Cancel',
  'common.save': 'Save',
  'common.search': 'Search',
  'common.more': 'More',
  'common.yes': 'Yes',
  'common.no': 'No',
  'common.minutes': 'minutes',
  'nav.home': 'Home',
  'nav.wishlist': 'Wishlist',
  'nav.mybids': 'My Bids',
  'nav.settings': 'Settings',
  'validators.required': 'This field is required',
  'validators.email': 'Please enter a valid email address',
  'validators.phone': 'Phone must be 8-15 digits',
  'validators.password': 'Password must be 8+ chars with upper, lower, digit and special',
  'validators.price': 'Price must be positive',
  'snackbar.error': 'Something went wrong',
  'snackbar.success': 'Saved successfully',
  'tutorial.step1': 'Swipe cards to discover auctions',
  'tutorial.step2': 'Add favorites with a single tap',
  'tutorial.step3': 'Switch language and theme anytime',
  'notifications.placeholder': 'Notifications will appear here soon',
  'offline.placeholder': 'Offline mode enabled using local storage',
  'weak.connection': 'Weak connection simulated',
  'coach.start': 'Start tour',
  'coach.next': 'Next tip',
  'coach.done': 'Finish',
  'ai.summary_1': 'AI summary: High market demand expected.',
  'ai.summary_2': 'AI summary: Stable value with moderate growth.',
  'ai.summary_3': 'AI summary: Consider maintenance costs.',
  'ai.summary_4': 'AI summary: Rare find with collector interest.',
  'ai.summary_5': 'AI summary: Competitive bids predicted.',
  'ai.demand_1': 'Demand index: Low competition currently.',
  'ai.demand_2': 'Demand index: Balanced buyer interest.',
  'ai.demand_3': 'Demand index: Multiple bidders watching.',
  'ai.rarity_1': 'Rarity: Common item in market.',
  'ai.rarity_2': 'Rarity: Slightly uncommon, nice catch.',
  'ai.rarity_3': 'Rarity: Regionally rare opportunity.',
  'ai.rarity_4': 'Rarity: Limited availability.',
  'ai.rarity_5': 'Rarity: Collector grade piece.',
  'ai.rarity_6': 'Rarity: One of a kind listing.',
  'ai.rarity_7': 'Rarity: Seasonal demand spike.',
  'ai.tip_1': 'Tip: Increase bid before final 2 minutes.',
  'ai.tip_2': 'Tip: Bundle with related accessories.',
  'ai.tip_3': 'Tip: Check inspection documents.',
  'ai.tip_4': 'Tip: Negotiate delivery terms early.',
  'ai.warning_1': 'Warning: Watch for sudden price jumps.',
  'ai.warning_2': 'Warning: Auction may close earlier than expected.',
};
